http://127.0.0.1:8080/api/hello


###

POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{
  "email": "test@email.com",
  "password": "password123"
}


###

POST http://127.0.0.1:8080/api/auth/register
content-type: application/json

{
  "email": "test@email.com",
  "username": "testuser",
  "password": "password123"
}

###

POST http://127.0.0.1:8080/api/auth/otp/generate
content-type: application/json

{
  "user_id": "84c4dee4-4ee0-4f42-8bab-8aca1c54b814",
  "email": "test@email.com"
}

# {
#   "otp_auth_url": "otpauth://totp/AuthApp:test@email.com?secret=T233UFCWW6GKEQCOYKLHX45FRVVKQDJBQ4&issuer=AuthApp",
#   "otp_base32": "T233UFCWW6GKEQCOYKLHX45FRVVKQDJBQ4"
# }

###

POST http://127.0.0.1:8080/api/auth/otp/verify
content-type: application/json

{
  "user_id": "84c4dee4-4ee0-4f42-8bab-8aca1c54b814",
  "token": "143888"
}

###
POST http://127.0.0.1:8080/api/auth/otp/validate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4NGM0ZGVlNC00ZWUwLTRmNDItOGJhYi04YWNhMWM1NGI4MTQiLCJleHAiOjE3NjI1OTczNTAsImF1ZCI6Im1mYS12ZXJpZmljYXRpb24iLCJhbXIiOlsicHdkIl19.Wm8xFfVB_dkxK-UcI_99y5x2IQsPGYMicThyozjBx0o123
content-type: application/json

{
  "user_id": "84c4dee4-4ee0-4f42-8bab-8aca1c54b814",
  "token": "145989"
}