-- Add migration script here
ALTER TABLE users
ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE,
ADD COLUMN otp_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN otp_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN otp_base32 TEXT,
ADD COLUMN otp_auth_url TEXT,
ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();